name: refresh-resolvers

#on:
#  push:
#    branches:
#      - main
on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  resfresh-list:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
    
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_SECRET }}

      - name: Checkout DNS Validator
        uses: actions/checkout@v2
        with:
          repository: 'vortexau/dnsvalidator'
          path: dnsvalidator
    
      - name: Install DNS Validator
        run: |
          cd dnsvalidator
          python3 setup.py install
    
      - name: Download sources
        run: |
          mkdir sources
          cd sources
          git clone https://github.com/trickest/resolvers
          git clone https://github.com/Abss0x7tbh/bass
          git clone https://github.com/cxosmo/dns-resolvers
          wget -O source1.txt https://public-dns.info/nameservers-all.txt
          wget -O source2.txt https://raw.githubusercontent.com/blechschmidt/massdns/master/lists/resolvers.txt
          wget -O source3.txt https://raw.githubusercontent.com/zeroc00I/test_github_action/main/resolvers.txt
          wget -O source4.txt https://raw.githubusercontent.com/carlospolop/Auto_Wordlists/5eacd91aabb3e5870fb398fba07d7061a3eac54b/wordlists/trusted_resolvers.txt
          wget -O source5.txt https://raw.githubusercontent.com/geraldino2/jart/fdefecdf4700a81c1cef525ad2764cb0b2f9e391/src/utils/base-resolvers.txt
          cd ..
          ls sources
          find sources -iname "*.txt"
          find sources -iname "*.txt" -exec cat {} + | sort -u > sources.txt
          wc -l sources.txt
      - name: Generate new resolvers
        run: dnsvalidator -tL sources.txt -threads 50 --silent > resolvers.txt
     
      - name: Commit changes
        run: |
          git config --local user.email "six2dez@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add resolvers.txt
          git commit -m "update"
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_SECRET }}
          branch: main
